### ISSUE TITLE
Known Languages not displaying

### ISSUE THREAD

**Issue by FerrocCaldrson** [TeaWithLucas/DNDBeyond-DM-Screen#4]
![122288019_1462533557265291_6856623932806135282_n](https://user-images.githubusercontent.com/68050533/96965292-23690800-14c9-11eb-9300-37df8652af35.jpg)
I see the label for "Known Languages" but none of them are actually displayed.
Just wanna say though I love this update and really appreciate the work done. It works amazingly, other than the small little bug previously mentioned.

**Comment by FerrocCaldrson** [comment]
I've done some fiddling with it, and found that one of the characters was set to "Private." Not only did this prevent the "Known Languages" from displaying, it also prevent the entire character's information from displaying on the main screen. Luckily, switching it to "Public" fixes the issue.

Not sure if that is intended or not, but did wanna give an update and say that the issue is resolved, though perhaps you'd consider looking into it if this was not intentional? Though maybe there isn't anything that can be done. Did wanna say once again though that I'm _loving_ this, it adds so much more convenience to my games.

**Comment by TeaWithLucas** [comment]
Thanks for identifying this, I do consider it a bug as you should be able to view private characters if you have permissions. I didn't consider that when testing so a good spot!
 I have now updated the script to use the person using the script's credentials and now it allows you to see characters that are private but you have permission to see, i.e. everyone in a campaign you are in! 
As this is done ill close this, feel free to report any other bugs!
